version: "3.9"
services:
  redis:
    image: redis:8.0.0-alpine
    container_name: fileuploader-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  postgres:
    image: postgres:17-alpine
    container_name: fileuploader-postgres
    environment:
      POSTGRES_USER: fileuploader
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fileuploaderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  redis_data:
  postgres_data:
