# Base image
FROM golang:1.24.5-alpine

# Sistem bağımlılıkları
RUN apk add --no-cache git bash

# Çalışma dizini
WORKDIR /file-uploader

# Go mod ve bağımlılıkları kopyala
COPY go.mod go.sum ./
RUN go mod download

# Tüm proje dosyalarını kopyala
COPY . .

# Worker main.go çalıştır
CMD ["go", "run", "cmd/worker/main.go"]
